---
- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
  - name: "Install {{ service }}"
    apt:
      name: "{{ service }}"
      state: latest
      update_cache: true
  - name: "Start {{ service }} Service"
    service:
      name: "{{ service }}"
      state: started