- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
  - repo: "https://github.com/omris-elda/SFIA-Project-2.git"
  tasks:
  - name: "Download Git Repo {{ repo }}"
    git:
      repo: "{{ repo }}"
      dest: /home/jenkins/Ansible/gitrepo