- hosts: localhost
  connection: local
  become: yes
  roles:
  - common
  - role: webserver
    vars:
      install_directory: /opt/static-website-example
      git_repository: https://gitlab.com/qacdevops/static-website-example