- hosts: docker
  become: true
  tasks:
    - name: Install Requirements for Docker
      apt:
        pkg: # this allows us to install multiple things at once
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        state: latest
        update_cache: true


    - name: Add official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present


    - name: Add apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable


    - name: Install Docker
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        state: latest
        update_cache: true


- hosts: nginx
  become: true
  tasks:
  - name: 'Install NGINX'
    apt:
      name: nginx
      state: latest
      update_cache: true
  - name: 'Start NGINX Service'
    service:
      name: nginx
      state: started
